version: '3'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
